### ISSUE TITLE
Padrão para contribuição

### ISSUE THREAD

**Issue by felipe-heredia** [flplima/laika#3]
Não sei como deveria ser o padrão de uma Issue, se inglês ou português, como meu inglês ainda é básico, preferi escrever em português já que não existe um padrão (ainda).

Eu gostaria muito de contribuir com o projeto, então você poderia escalar as contribuições criando algumas coisas como:

- Um arquivo em Markdown explicando como podemos contribuir e quais são os padrões desejados.
- Criar um padrão para issues.
- Explicando como funciona o arquivamento das mensagens, se elas são guardadas no banco de dados e se é possível o usuário fornecer uma resposta a mais para ser guardada no banco, visto que o sistema é uma IA e deve aprender sozinha a cada dia para que possa ser melhor etc.

**Comment by flplima** [comment]
Olá, Felipe. Agradeço o interesse em contribuir com o projeto!

Nesse fim de semana irei subir um markdown explicando melhor como contribuir e definir os padrões.

Penso que para as próximas issues, assim como para todo o código e mensagens de commit, seria legal usarmos apenas o inglês. Meu inglês também é básico ainda e uso bastante o Google Tradutor. Mas acredito que, padronizando em inglês, mais pessoas de outros países também poderão acompanhar as discussões e contribuir. O que acha? 

Sobre o arquivamento das mensagens: Sim, todas as mensagens são guardadas no banco MongoDB, isso é feito pelo [messages.service.ts](https://github.com/flplima/laika/blob/master/server/src/core/messages/messages.service.ts). Elas podem ser acessadas usando o sistema de injeção de dependência do NestJS. Inclusive você pode criar suas próprias collections para extrair dados das mensagens e armazenar apenas o que for relevante.
Tem um exemplo interessante no módulo [Skills/Notes](https://github.com/flplima/laika/blob/master/server/src/skills/notes/) onde você pode pedir para a Laika salvar uma nota, e depois pedir pra ela trazer as notas salvas para você. Ela salva no mesmo banco de dados MongoDB. Veja como funciona no arquivo [notes.service.ts](https://github.com/flplima/laika/blob/master/server/src/skills/notes/notes.service.ts)

Você pode ver mais sobre como o NestJS e o MongoDB funcionam juntos lendo a documentação abaixo:
https://docs.nestjs.com/techniques/mongodb

Depois vou documentar melhor como tudo isso funciona. Inclusive adicionar um README para cada skill.

Obrigado pela contribuição!
